"""empty message

Revision ID: 88abe2b683df
Revises: d5ed832ac4af
Create Date: 2022-12-10 17:15:29.064199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88abe2b683df'
down_revision = 'd5ed832ac4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('types', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('abilities', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('sprite', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('pokemon_name_key', type_='unique')
        batch_op.drop_column('poke_type')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poke_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('pokemon_name_key', ['name'])
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')
        batch_op.drop_column('sprite')
        batch_op.drop_column('abilities')
        batch_op.drop_column('types')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
